export const MARTA_STATIONS = [
    {value: 'AIRPORT STATION', label: 'Airport'},
    {value: 'ARTS CENTER STATION', label: 'Arts Center'},
    {value: 'ASHBY STATION', label: 'Ashby'},
    {value: 'AVONDALE STATION', label: 'Avondale'},
    {value: 'BANKHEAD STATION', label: 'Bankhead'},
    {value: 'BROOKHAVEN STATION', label: 'Brookhaven'},
    {value: 'BUCKHEAD STATION', label: 'Buckhead'},
    {value: 'CHAMBLEE STATION', label: 'Chamblee'},
    {value: 'CIVIC CENTER STATION', label: 'Civic Center'},
    {value: 'COLLEGE PARK STATION', label: 'College Park'},
    {value: 'DECATUR STATION', label: 'Decatur'},
    {value: 'DORAVILLE STATION', label: 'Doraville'},
    {value: 'DUNWOODY STATION', label: 'Dunwoody'},
    {value: 'EAST LAKE STATION', label: 'East Lake'},
    {value: 'EAST POINT STATION', label: 'East Point'},
    {value: 'EDGEWOOD CANDLER PARK STATION', label: 'Edgewood/Candler Park'},
    {value: 'FIVE POINTS STATION', label: 'Five Points'},
    {value: 'GARNETT STATION', label: 'Garnett'},
    {value: 'GEORGIA STATE STATION', label: 'Georgia State'},
    {value: 'INDIAN CREEK STATION', label: 'Indian Creek'},
    {value: 'KENSINGTON STATION', label: 'Kensington'},
    {value: 'KING MEMORIAL STATION', label: 'King Memorial'},
    {value: 'LENOX STATION', label: 'Lenox'},
    {value: 'LINDBERGH STATION', label: 'Lindberg'},
    {value: 'MEDICAL CENTER STATION', label: 'Medical Center'},
    {value: 'MIDTOWN STATION', label: 'Midtown'},
    {value: 'NORTH AVE STATION', label: 'North Avenue'},
    {value: 'NORTH SPRINGS STATION', label: 'North Springs'},
    {value: 'OAKLAND CITY STATION', label: 'Oakland City'},
    {value: 'PEACHTREE CENTER STATION', label: 'Peachtree Center'},
    {value: 'SANDY SPRINGS STATION', label: 'Sandy Springs'},
    {value: 'VINE CITY STATION', label: 'Vine City'},
    {value: 'WEST END STATION', label: 'West End'},
    {value: 'WEST LAKE STATION', label: 'West Lake'}
];
